### ISSUE TITLE
Comick API + ID changes.

### ISSUE THREAD

**Issue by meotimdihia** [tachiyomiorg/tachiyomi-extensions#14788]
### Source information and language

comickfun (all)

### Source new URL

https://api.comick.fun/

### Other details

`https://api.comick.fun/comic/{id}/chapter`(deprecated) will change to `https://api.comick.fun/comic/{hid}/chapters`

And please map `slug` to `hid` as Comic ID. Because sometimes, we'll change the slug and the user list will miss the comic that has the slug that was changed.

For example: [https://api.comick.fun/tachiyomi/mapping?slugs=naruto&slugs=one-piece](https://api.comick.fun/tachiyomi/mapping?slugs=naruto&slugs=one-piece)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated all installed extensions.
- [X] I have checked if the source URL is not already updated by opening WebView.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Closed by #14842

**Comment by vetleledaal** [comment]
> Closed by #14842

That PR:
> The slug and hid changes in https://github.com/tachiyomiorg/tachiyomi-extensions/issues/14788 have not been addressed in this PR.

**Comment by meotimdihia** [comment]
And the API `/tachiyomi/mapping` can map many slugs at once too. (to avoid making too many requests, the API platform will block them)

**Comment by alessandrojean** [comment]
I've only read the first part of the PR body and assumed everything was addressed, my bad. Issue reopened.

**Comment by meotimdihia** [comment]
Hi, I still see many requests to the APIs https://api.comick.fun/tachiyomi/mapping?slugs=naruto&slugs=one-piece
Did we really replace `slug` with `hid` to avoid requesting the API again?

**Comment by alessandrojean** [comment]
The extensions expect a URL to be saved and it should match the site one, so the user can click Open in WebView and it opens the site (with the most updated slug/URL). Since we can't store the slug anymore as it will be changed over time, is there a possibility instead you add an alternative URL in the site that allows the `hid`?

For example, `https://comick.app/comic/{hid}` or `https://comick.app/comic/hid/{hid}`. Allowing this will make the extension development easier and the extension wouldn't need to store the slugs and neither request the mapping API endpoint anymore.

**Comment by meotimdihia** [comment]
@alessandrojean I did it. You can access the comic info by `{hid}` now.
And we shouldn't store the `slug` as it will be changed.
