### ISSUE TITLE
Mangahub gives an error on Chapter refresh 

### ISSUE THREAD

**Issue by ShravanAshok16** [tachiyomiorg/tachiyomi-extensions#15185]
### Source information and language

Mangahub 1.3.22

### Steps to reproduce

1.Navigate to Mangahub
2.Select any managa
3.Refresh the chapters of the selected manga

### Expected behavior

The new chapters for the selected manga should be updated and displayed

### Actual behavior

Is giving a Java Null pointer exception on Chapter refresh
![Screenshot_2023-01-31-02-29-49-76_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/115018563/215594993-4053c909-12db-42ed-8246-f13a4de832cb.jpg)

### Tachiyomi version

0.14.3

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
> I have updated all installed extensions.

Follow the acknowledgements section and update your extensions first. This is already fixed.

**Comment by ShravanAshok16** [comment]
Updated the extension but still experiencing th same err
![Screenshot_2023-01-31-11-51-25-62_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/115018563/215682619-5b71b2a5-cb3d-48c2-9a30-a1d28a5b593d.jpg)
or
