### ISSUE TITLE
Fix http error 403 

### ISSUE THREAD

**Issue by positivnii** [tachiyomiorg/tachiyomi-extensions#15868]
### Source information and language

Remanga (RU)

### Steps to reproduce

403 http error

### Expected behavior

it won't let me access the titles 

### Actual behavior

//

### Tachiyomi version

0.14.5

### Android version

Android 11

### Other details

Extension version 1.4.67

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
@e-shl said this was fixed in 1.4.67 in https://github.com/tachiyomiorg/tachiyomi-extensions/pull/15870#issuecomment-1486925516 but the original poster said it happened in 1.4.67.

**Comment by e-shl** [comment]
> Extension version 1.4.67

in this version, the 403 bug was fixed for Ukraine internet-providers.

**Comment by positivnii** [comment]
I have the http 403 problem not solved I have tried everything I come from Italy

**Comment by e-shl** [comment]
> from Italy

The site has internal restrictions on regions. See what the site itself writes.

**Comment by e-shl** [comment]
>403 Italy

I checked through vpn. Domain remanga.org available both in Tachiyomi and from the browser. But domain mirror реманга.орг issues 403 only in Tachiyomi as Ukrainian internet-providers up to 67.
![Screenshot_20230329-072406438.jpg](https://user-images.githubusercontent.com/35057681/228410269-2a5a09ba-9f6e-4426-a7d1-5f2f7c22f578.jpg)

**Comment by e-shl** [comment]
> Can you fix it ?

Go back to main domain. If it doesn't help, I'm not sure what I can fix already.

**Comment by positivnii** [comment]
I'm on main doman ,from browser and webview all works only from Tachiyomi it gives me a 403 error

**Comment by positivnii** [comment]
thank you all the same
