### ISSUE TITLE
[Source Request] <ComicK>

### ISSUE THREAD

**Issue by laganeyt** [tachiyomiorg/tachiyomi-extensions#5680]
## Source website
- Name: Comick
- Link: https://comick.fun/
- Language(s): English and more

## Other details
They mirror Mangadex (supposedly)

**Comment by meotimdihia** [comment]
> https://comick.fun is the Mangadex mirror. It has whole Mangadex comics.
> And while Mangadex is down. Comick is still alive, update comics.
> In the future, it could have diverse other sources
> 
> Comick.fun has integrated with Graphql API . It is very easy to intergrate, I think.

I quote it again from another issue.

**Comment by CarlosEsco** [comment]
Do they have documentation for their api?

**Comment by meotimdihia** [comment]
I'm a comick dev. Currently, I am learning how to make Tachiyomi extensions.
I could pull a request in the next few days.

**Comment by meotimdihia** [comment]
@CarlosEsco I am dev Comick. I can write documentation about the API.
Currently, I just use HTTP API. About Graphql, it doesn't have strong security for now.

**Comment by CarlosEsco** [comment]
I was looking into earlier. The one end point I couldn't find was getting the manga info itself.  If you need help feel free to join the discord channel and ask in #programming

**Comment by meotimdihia** [comment]
If you are wanting to help Comick develop a Tachiyomi extension. I can create an API to get manga information in hours.

**Comment by h-hyuuga** [comment]
@meotimdihia  

Is there anything you'd like us to be considerate of as we implement this? (i.e rate-limiting etc...)

**Comment by meotimdihia** [comment]
Thanks, everyone on my site is requesting the Tachiyomi extension but I don't have experience with Kotlin.
And currently, I don't have any problem with this.

**Comment by h-hyuuga** [comment]
> Thanks, everyone on my site is requesting the Tachiyomi extension but I don't have experience with Kotlin.
> And currently, I don't have any problem with this. 😀


Cool!

The current plan is to make it obvious what traffic is coming from us (user agent contains the string "Tachiyomi"), so you can notify us as needed.



If you're open to feature requests in your API:

* `/api/get_newest_chapters` responds with status code `429` when it decides to stop returning data. The 400 range denotes that some error occured, but that's not really what happened. If possible, could you change this to something in the 200 range? `204` (No Content) would make sense since the api has no content to return.

**Comment by meotimdihia** [comment]
Ok, I will change code 429 to 204.
And I have a question:  
I am going to create a new API to fetch Manga info, ex `/api/get_comic?slug=one-punch-man`. Do you need that API?

**Comment by h-hyuuga** [comment]
Not particularly? 

I'm not sure if this is meant to be public but `https://comick.fun/_next/data/BASE64_ID/comic/SLUG.json` seems to return what I'd expect to get from `/api/get_comic?slug=SLUG`

**Comment by meotimdihia** [comment]
But that BASE64_ID on the URL, will be changed when I deploy a new build.
Unless you fetch full HTML and parse to get a new URL.
And I think we should use APIs, it is better than for the future.

**Comment by h-hyuuga** [comment]
Got it, then yes that endpoint would be great!

**Comment by meotimdihia** [comment]
I added 2 APIs:
- Get comic info by slug, ex: https://comick.fun/api/get_comic?slug=romance-101
- Get chapter info by hid, ex: https://comick.fun/api/get_chapter?hid=r7Jyp

**Comment by h-hyuuga** [comment]
Would it be feasible to include the scanlation group in the response from `/api/get_chapter`

**Comment by meotimdihia** [comment]
Scanlation group was included in the response, it is "group_name" or "md_chapters_groups". 😀

**Comment by h-hyuuga** [comment]
* Is the limit for `/api/get_chapters`  guaranteed to be 100 chapters per page?
* Am I right to assume that `/api/search_title` isn't paginated

**Comment by meotimdihia** [comment]
Hi, 
- `/api/search_title` isn't paginated, it returned the most similar results.
- I add the params `limit` to `api/get_chapters` to return all chapters if you want to.

**Comment by h-hyuuga** [comment]
Adding a limit to `/api/get_chapters` is up to you. 

I have the extension working without explicitly knowing the page limit. But I can make it _slightly_ better (optimize out a request) if I know what the page limit is.

**Comment by meotimdihia** [comment]
I added the `limit` param. You should use it because I usually change defaults.
`https://comick.fun/api/get_chapters?comicid=27095&page=1&limit=99999`

**Comment by h-hyuuga** [comment]
I think I found a bug

Solo Leveling has 1002 chapters. I would imagine that with `limit=50`, there would be 21 pages. But we run out of results after page 12

https://comick.fun/api/get_chapters?comicid=27095&page=12&limit=50

**Comment by meotimdihia** [comment]
I fixed the bug :D.
And I updated APIs to support Taychiomi. APIs will return a little different when the client request `user-agent` header contains `Tachiyomi` string or param `tachiyomi`. For examples: 
- https://comick.fun/api/get_chapter?hid=r7Jyp&tachiyomi=1
- https://comick.fun/api/get_chapter?hid=r7Jyp

**Comment by h-hyuuga** [comment]
in `/api/search` the "Minimum Chapter"  param is misspelled

The server expects a param called `mini***n***um` instead of `mini***m***um`.

**Comment by meotimdihia** [comment]
Thanks, I just have fixed the spelling 😅

**Comment by h-hyuuga** [comment]
> I fixed the bug :D.
> And I updated APIs to support Taychiomi. APIs will return a little different when the client request `user-agent` header contains `Tachiyomi` string or param `tachiyomi`. For examples:
> 
> * https://comick.fun/api/get_chapter?hid=r7Jyp&tachiyomi=1 - Added coverURL for comic.
> * https://comick.fun/api/get_chapter?hid=r7Jyp
> * https://comick.fun/api/get_newest_chapters?page=0&tachiyomi=1 - Added coverURL for comics.
> * https://comick.fun/api/get_newest_chapters?page=0

I'm pretty sure this introduced a Tachiyomi  specific bug.

After this update, I noticed that I'd somewhat frequently get `Http 500`s when requesting from `/api/search` or `/api/search_title`. This only happened when the user-agent contained the string Tachiyomi (specific user agent used was `Tachiyomi Dalvik/2.1.0 (Linux; U; Android 11; sdk_gphone_x86_arm Build/RSR1.201013.001)`)

The frequency of the issue seems to be mitigated by some  network cache:

* Paging through the results of `https://comick.fun/api/search?page=PAGE&limit=100` doesn't return 500 until we get to a  later page number (i.e device is getting cached response, but a cache miss forces the request to go all the way to the server where it returns 500). Repeating the erroring request with a user-agent without `Tachiyomi` will succeed.

* `https://comick.fun/api/search_title?t=1&q=QUERY` will sometimes succeed if the query had been cached. But it's pretty easy to come up with a query that'll lead to a 500.


---

If the special case added for Tachiyomi is the problem, feel free to roll it back. The extension as written can handle getting covers using either `coverURL` or `md_covers`, so it doesn't really matter to me.

**Comment by meotimdihia** [comment]
I fixed the bugs.
You can't use the `md_covers` value, it is raw data and Comick frontend has to edit it too. 
And by using `coverURL`, I can migrate images to another source in the future. 😀

**Comment by h-hyuuga** [comment]
I can still reproduce the same issue.

I'm not sure if I need to wait for the changes to propogate, but 20 minutes after your message I can still reproduce the issue.


You should be able to test this yourself by sending requests with the following user agent  `Tachiyomi Dalvik/2.1.0 (Linux; U; Android 11; sdk_gphone_x86_arm Build/RSR1.201013.001)`

* `https://comick.fun/api/search?page=PAGE&limit=100` -> try for various values of PAGE
* `https://comick.fun/api/search_title?t=1&q=QUERY`  -> try for different queries

**Comment by meotimdihia** [comment]
Sorry, my deployment was failed, I forgot to check the deployment status before post this. 😅

It deployed successfully now.

**Comment by meotimdihia** [comment]
The bug still happened. I am checking again O___O

**Comment by meotimdihia** [comment]
Fixed the bug and deployed the build successfully to production.

**Comment by h-hyuuga** [comment]
Sweet, I can't reproduce anymore

I have a PR (#7159) waiting to be merged which'll add the site to tachiyomi
