### ISSUE TITLE
[Bug] <MangaPill>: Manga from MangaPill do not appear in Updates section

### ISSUE THREAD

**Issue by patros36** [tachiyomiorg/tachiyomi-extensions#6331]
## Device information
- Tachiyomi version: 0.10.9
- Android version: 10 QKQ1

## Source information
- Name: MangaPill
- Extension version: 1.2.1

## Steps to reproduce
1. Add a manga (BnHA in my case) to your library.
2. Update library.

### Expected behavior
Manga should update and the new chapter should appear in the Updates section of tachiyomi.

### Actual behavior
Manga updates, but the new chapter does not appear in the Updates section, so if you don't browse the library tab, you won't know there's a new chapter.

## Other details
I haven't tried it with any other manga BnHA is the only manga i have on this source, so i don't know if its a problem with the extension or just that title. Sorry.

**Comment by scb261** [comment]
That's because the site doesn't provide upload dates. This was actually fixed in tachi preview, where it uses fetch date, but it caused new issues like flooding the Updates section with old chapters when migrating, so no guarantee it will stay.

Anyway, not fixable on the extension side unless the site will start providing dates.

**Comment by patros36** [comment]
Oh makes sense, good to know, thanks.
But the Update section flooding still happens when i migrate to other sources. Are those bugs too? Just curious.

**Comment by scb261** [comment]
tachiyomiorg/tachiyomi#4732

Use https://discord.gg/tachiyomi if you have more questions.
